alias gk='gitk --all'
alias gres='git reset --hard ; git clean -fdx ; git submodule foreach git reset --hard ; git submodule foreach git clean -fdx'
alias gu='git gui'
alias gf='git fetch origin'
alias gfa='git fetch origin ; git submodules foreach git fetch origin'
